### ISSUE TITLE
There are no more proxies

### ISSUE THREAD

**Issue by WayneChen007** [BlueSkyXN/CCATK#1]
> Checked 6280 proxies
> Checked all proxies, Total Worked:0
> Do u want to save them in a file? (y/n, default=y)
> They are saved in socks4.txt.
> There are no more proxies. Please download a new one.

**Comment by BlueSkyXN** [comment]
> > Checked 6280 proxies
> > Checked all proxies, Total Worked:0
> > Do u want to save them in a file? (y/n, default=y)
> > They are saved in socks4.txt.
> > There are no more proxies. Please download a new one.

Try socks5
According to my own experience, there are generally more than 200 available, or you can find the list of available agents by yourself
